version: "3.9"

services:
  motivation-bot:
    container_name: go-motivation-bot
    build:
      context: app/motivation-bot
      dockerfile: Dockerfile_dev
    restart: "no"
    ports:
      - "8181:8080"
      - "2345:2345"
    environment:
      GOTRACEBACK: all # Flag for debug
    volumes:
      - ./app/motivation-bot:/app
    env_file:
      - ./app/motivation-bot/.env.loc
    depends_on:
      - go-motivation-mongodb

  go-motivation-mongodb:
    image: mongo:4-focal
    container_name: go-motivation-bot-mongo
    restart: "no"
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: go-motivation-bot-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password1
      MONGO_USERNAME: user
      MONGO_PASSWORD: password1
    volumes:
      - './init-mongodb.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro'